### ISSUE TITLE
PhantomJS is deprecated

### ISSUE THREAD

**Issue by WildOne69** [lateralblast/oort#1]
im on MacOS Mojave 10.14.6, due to PhantomJS is deprecated i get the following without the firmware info as you can see below:

./oort.rb -m t5220
T5220:
2019-09-01 23:03:53 WARN Selenium [DEPRECATION] Selenium support for PhantomJS is deprecated. Use headless Chrome/Firefox or HTMLUnit instead.
/Library/Ruby/Site/2.3.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- selenium/webdriver/phantomjs (LoadError)
	from /Library/Ruby/Site/2.3.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/me/.rvm/gems/ruby-2.6.3/gems/selenium-webdriver-3.142.3/lib/selenium/webdriver/common/driver.rb:52:in `for'
	from /Users/me/.rvm/gems/ruby-2.6.3/gems/selenium-webdriver-3.142.3/lib/selenium/webdriver.rb:88:in `for'
	from ./oort.rb:1269:in `get_mos_url'
	from ./oort.rb:1658:in `get_aru_no'
	from ./oort.rb:1715:in `get_oracle_readme_url'
	from ./oort.rb:1691:in `get_obp_ver'
	from ./oort.rb:2119:in `block in print_output'
	from ./oort.rb:2102:in `each'
	from ./oort.rb:2102:in `print_output'
	from ./oort.rb:2174:in `handle_fw_output'
	from ./oort.rb:2552:in `<main>'

i looked around in the code but it looks a bit more complicated than i want to dig into to try to fix.

**Comment by richardatlateralblast** [comment]
I quickly replaced phantomjs with firefox in headless mode and fixed MOS login. It appears to work now. I can't test download capability as I don't have an Oracle account tied to a CSI with access to patches.

 ./oort.rb -m t5220                                                                      
T5220:
Sun SPARC Enterprise T5220 Server SysFW 7.4.11 (based on ILOM 3.0) 147307-15 OBP 4.33.6.h
https://support.oracle.com/epmos/faces/ui/patch/PatchDetail.jspx?patchId=147307-15
https://getupdates.oracle.com/all_unsigned/147307-15.zip
T5220 SysFW 7.3.3 (based on ILOM 3.0) 145673-05 OBP 4.32.5.a
https://support.oracle.com/epmos/faces/ui/patch/PatchDetail.jspx?patchId=145673-05
https://getupdates.oracle.com/all_unsigned/145673-05.zip
T5220 SysFW 7.2.11 (based on ILOM 3.0) 139439-14 OBP 4.30.10
https://support.oracle.com/epmos/faces/ui/patch/PatchDetail.jspx?patchId=139439-14
https://getupdates.oracle.com/all_unsigned/139439-14.zip
T5220 SysFW 7.1.8.a (based on ILOM 2.0) 136932-10 OBP 4.29.2
https://support.oracle.com/epmos/faces/ui/patch/PatchDetail.jspx?patchId=136932-10
https://getupdates.oracle.com/all_unsigned/136932-10.zip
T5220 SysFW 7.0.9.c (based on ILOM 2.0) 127580-05 OBP 4.27.10
https://support.oracle.com/epmos/faces/ui/patch/PatchDetail.jspx?patchId=127580-05
https://getupdates.oracle.com/all_unsigned/127580-05.zip
