### ISSUE TITLE
http redirects dont work on Ruby pre 2.4

### ISSUE THREAD

**Issue by WildOne69** [lateralblast/oort#2]
Macbook Pro with Latest MacOS Mojave 10.14.6 installed:

Shouldn't the project be using https by default in the script??

and yes I realize I should update Ruby by hand to 2.4 BUT apple is running old Ruby.

MacBook-Pro-4:oort me$ ruby --version
ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
MacBook-Pro-4:oort me$ 

MacBook-Pro-4:oort me$ ./oort.rb -m T5220
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/open-uri.rb:225:in `open_loop': redirection forbidden: http://www.oracle.com/technetwork/systems/patches/firmware/release-history-jsp-138416.html -> https://www.oracle.com/technetwork/systems/patches/firmware/release-history-jsp-138416.html (RuntimeError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/open-uri.rb:151:in `open_uri'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/open-uri.rb:717:in `open'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/open-uri.rb:35:in `open'
	from ./oort.rb:1461:in `search_system_fw_page'
	from ./oort.rb:2551:in `<main>'

**Comment by richardatlateralblast** [comment]
Yes https should be default, but when I originally wrote all that time ago the SSL support in Ruby's open-uri was horridly broken, thus why I generally write in python these days. If I get a chance I'll look at https again. I'll update all the URLs to https, I'm not sure if that'll break the downloads or not. It might fix your problem though.

**Comment by WildOne69** [comment]
i manually fixed that one to https:// and it fixed the problem for me.

**Comment by richardatlateralblast** [comment]
Cool. I've updated and pushed it with https URLs. Unfortunately I can't test the download, but it did appear to try to fetch the file.
