### ISSUE TITLE
-n doesnt cover E3x00/E4x00/E5x00/E6x00

### ISSUE THREAD

**Issue by WildOne69** [lateralblast/oort#3]
I noticed while doing a 
oort.rb -n all 
it doesnt display anything for E3x00/E4x00/E5x00/E6x00 series

poking in the patchdiag.xref i grabbed from oracle:
cat patchdiag.xref | grep "4x00"

103346|30|Oct/30/02| | | |  |Unbundled|||Hardware/PROM: Sun Enterprise 3x00/4x00/5x00/6x00 flashprom update

**Comment by richardatlateralblast** [comment]
By no means perfect, but added some handling:

./oort.rb -n all 
E6900:
E3500 E4500 E5500 E6500 E3800 E4800 E6800 E4900 E6900 flashprom update POST 3.9.30 OBP 3.2.30
https://support.oracle.com/epmos/faces/ui/patch/PatchDetail.jspx?patchId=103346-30
https://getupdates.oracle.com/all_unsigned/103346-30.zip
E4900:
E3500 E4500 E5500 E6500 E3800 E4800 E6800 E4900 E6900 flashprom update POST 3.9.30 OBP 3.2.30
https://support.oracle.com/epmos/faces/ui/patch/PatchDetail.jspx?patchId=103346-30
https://getupdates.oracle.com/all_unsigned/103346-30.zip
E6800:
E3500 E4500 E5500 E6500 E3800 E4800 E6800 E4900 E6900 flashprom update POST 3.9.30 OBP 3.2.30
https://support.oracle.com/epmos/faces/ui/patch/PatchDetail.jspx?patchId=103346-30
https://getupdates.oracle.com/all_unsigned/103346-30.zip
E4800:
E3500 E4500 E5500 E6500 E3800 E4800 E6800 E4900 E6900 flashprom update POST 3.9.30 OBP 3.2.30
https://support.oracle.com/epmos/faces/ui/patch/PatchDetail.jspx?patchId=103346-30
https://getupdates.oracle.com/all_unsigned/103346-30.zip
E3500:
E3500 E4500 E5500 E6500 E3800 E4800 E6800 E4900 E6900 flashprom update POST 3.9.30 OBP 3.2.30
https://support.oracle.com/epmos/faces/ui/patch/PatchDetail.jspx?patchId=103346-30
https://getupdates.oracle.com/all_unsigned/103346-30.zip
E4500:
E3500 E4500 E5500 E6500 E3800 E4800 E6800 E4900 E6900 flashprom update POST 3.9.30 OBP 3.2.30
https://support.oracle.com/epmos/faces/ui/patch/PatchDetail.jspx?patchId=103346-30
https://getupdates.oracle.com/all_unsigned/103346-30.zip
E5500:
E3500 E4500 E5500 E6500 E3800 E4800 E6800 E4900 E6900 flashprom update POST 3.9.30 OBP 3.2.30
https://support.oracle.com/epmos/faces/ui/patch/PatchDetail.jspx?patchId=103346-30
https://getupdates.oracle.com/all_unsigned/103346-30.zip
E6500:
E3500 E4500 E5500 E6500 E3800 E4800 E6800 E4900 E6900 flashprom update POST 3.9.30 OBP 3.2.30
https://support.oracle.com/epmos/faces/ui/patch/PatchDetail.jspx?patchId=103346-30
https://getupdates.oracle.com/all_unsigned/103346-30.zip
E3800:
E3500 E4500 E5500 E6500 E3800 E4800 E6800 E4900 E6900 flashprom update POST 3.9.30 OBP 3.2.30
https://support.oracle.com/epmos/faces/ui/patch/PatchDetail.jspx?patchId=103346-30
https://getupdates.oracle.com/all_unsigned/103346-30.zip
