### ISSUE TITLE
-n E4500 finds nothing but -n all displays it

### ISSUE THREAD

**Issue by WildOne69** [lateralblast/oort#5]
Back again, thanks for the quick updates and fixes for everything so far

./oort.rb -n all
<snip>
E3500:
E3500 E4500 E5500 E6500 E3800 E4800 E6800 E4900 E6900 flashprom update POST 3.9.30 OBP 3.2.30
https://support.oracle.com/epmos/faces/ui/patch/PatchDetail.jspx?patchId=103346-30
https://getupdates.oracle.com/all_unsigned/103346-30.zip
E4500:
E3500 E4500 E5500 E6500 E3800 E4800 E6800 E4900 E6900 flashprom update POST 3.9.30 OBP 3.2.30
https://support.oracle.com/epmos/faces/ui/patch/PatchDetail.jspx?patchId=103346-30
https://getupdates.oracle.com/all_unsigned/103346-30.zip
E5500:
E3500 E4500 E5500 E6500 E3800 E4800 E6800 E4900 E6900 flashprom update POST 3.9.30 OBP 3.2.30
https://support.oracle.com/epmos/faces/ui/patch/PatchDetail.jspx?patchId=103346-30
https://getupdates.oracle.com/all_unsigned/103346-30.zip
E6500:
E3500 E4500 E5500 E6500 E3800 E4800 E6800 E4900 E6900 flashprom update POST 3.9.30 OBP 3.2.30
https://support.oracle.com/epmos/faces/ui/patch/PatchDetail.jspx?patchId=103346-30
https://getupdates.oracle.com/all_unsigned/103346-30.zip
<snip>

./oort.rb -n E4500
MacBook-Pro-4:oort me$

**Comment by richardatlateralblast** [comment]
Did a quick fix, should now work.

./oort.rb -n E4500
E4500:
E3500 E4500 E5500 E6500 E3800 E4800 E6800 E4900 E6900 flashprom update POST 3.9.30 OBP 3.2.30
https://support.oracle.com/epmos/faces/ui/patch/PatchDetail.jspx?patchId=103346-30
https://getupdates.oracle.com/all_unsigned/103346-30.zip
