### ISSUE TITLE
E3500/E4500/E5500/E6500 is working , BUT E3000/E4000/E5000/E6000 isnt

### ISSUE THREAD

**Issue by WildOne69** [lateralblast/oort#6]
so now that E3500/E4500/E5500/E6500 is working, BUT E3000/E4000/E5000/E6000 isn't yet.

I'm not sure how to submit a pull request but I figured out how to add it in the script and im not familiar with git much.

**Comment by richardatlateralblast** [comment]
Did another quick fix, should now work.
