### ISSUE TITLE
Enhancement: check for Fcode for platforms that have Fcode updates.

### ISSUE THREAD

**Issue by WildOne69** [lateralblast/oort#7]
i added "Fcode" to the end of check_strings to look thru patchdiag.xref for platforms that have Fcode patches like the SunFire T2000.

              check_strings = [ "ILOM", "Hostconfig", "Hypervisor", "OpenBoot",
                                "POST", "OBP", "System Firmware", "ScApp",
                                "PROM", "RTOS", "FCode" ]

seens to work fine 

./oort.rb -m T2000
T2000:
Sun Fire T2000 Server SPARC Enterprise (requires SysFW 6.3 or later) 6.7.13 139434-10 OBP 4.30.4.e
https://support.oracle.com/epmos/faces/ui/patch/PatchDetail.jspx?patchId=139434-10
https://getupdates.oracle.com/all_unsigned/139434-10.zip
<snip>
T2000 LSI 1064 FCode FW Update for 3041XL PCI-X Add-in Card 122165-02
https://support.oracle.com/epmos/faces/ui/patch/PatchDetail.jspx?patchId=122165-02
https://getupdates.oracle.com/all_unsigned/122165-02.zip

**Comment by richardatlateralblast** [comment]
Thanks! added FCode
