### ISSUE TITLE
Possible enhancement: Tape Library and Tape drive firmware

### ISSUE THREAD

**Issue by WildOne69** [lateralblast/oort#8]
after poking thru patchdiag.xref i came across Tape library firmware and tape library robot firmware.

how hard would it be to add this to oort? from my poking thru the code , it looks somewhat simple as your code is well organized. im willing to help where i can.

MacBook-Pro-4:~ me$ cat patchdiag.xref | grep "Tape"
106789|01|Nov/05/98| | |O|  |Unbundled|||Obsoleted by: 108437-04 Hardware, Tape: ETL 4/1000, 4/1800, 7/3500
107502|01|Mar/17/99| | | |  |Unbundled|||Hardware, Tape: L280 autoloader / Libraries
107592|01|Apr/21/99| | | |  |Unbundled|||Hardware, Tape: DLT4000, 4700 Probe-scsi corrupt output
108402|01|Nov/17/99| | | |  |Unbundled|||Hardware,DDS-3 4mm Tape Drive: Firmware Download Program L910 firm
108406|02|Aug/17/00| | | |  |Unbundled|||Hardware, Tape Library, L11000
108408|03|Feb/03/04| | | |  |Unbundled|||Hardware, DLT7000 Tape Drive, Firmware Download Program, V109
108437|06|Feb/11/04| | | |  |Unbundled|||Hardware, DLT7000 Tape Drive, Firmware Download Program, V109
108598|03|Apr/21/00| | | |  |Unbundled|108437-02;||Hardware, Tape: L1800,  Libraries
108917|04|Mar/16/04| | | |  |Unbundled|||Hardware, Quantum DLT7000 Tape Drive, Firmware Download Program, V
108918|02|Aug/02/00| | | |  |Unbundled|||Hardware, Tape: L280 autoloader / Libraries
109780|01|Jul/13/00| | | |  |Unbundled|||Hardware, Tape: L1000,  Libraries
110025|01|Aug/21/00| | | |  |Unbundled|||Hardware, Tape Library, L11000
112067|02|Dec/19/03| | | |  |Unbundled|||Hardware, DLT8000 Flexipack Tape Drive, Firmware Download Program,
112068|02|Apr/29/04| | | |  |Unbundled|||Hardware, Quantum DLT8000 Tape Drive, Firmware Download Program, V
112069|01|Feb/27/02| | | |  |Unbundled|108437-04;||Hardware, Tape: L3500, Libraries
112092|01|Oct/23/01| | | |  |Unbundled||108402-01;|Hardware/Tape: DDS-3 4mm Tape Drive Firmware Download Program L007
112093|01|Oct/23/01| | | |  |Unbundled|||Hardware DDS-3 4mm Tape Autoloader Firmware Version U007
112094|01|Nov/01/01| | | |  |Unbundled|||Hardware, DDS-4 4mm Tape Drive, Firmware Download Program C005
113359|01|Apr/08/03| | | |  |Unbundled|||Hardware, HP Ultrium-1 LTO Tape Drive, Firmware Download Program E
115917|03|Jan/10/05| | | |  |Unbundled|||Hardware, LTO-1 Tape Drive, Firmware Download Program V1613
116165|04|Sep/22/05| | | |  |Unbundled|||Hardware, L25/L100 Tape Library, Firmware, V12
116166|05|Jul/31/07| | | |  |Unbundled|||Hardware, SDLT320/SDLT220 Tape Drive, Firmware Download Program, V
116167|02|Feb/10/05| | | |  |Unbundled|||Hardware, SDLT320/SDLT220 Automation Tape Drive, Firmware Download
116168|02|Oct/28/04| | | |  |Unbundled|||Hardware, Tape Library, Management Card Firmware, V4.3.1
116169|01|May/28/04| | | |  |Unbundled|||Hardware, HP Ultrium-1 LTO Tape Drive, Firmware Download Program E
116170|03|Jul/20/06| | | |  |Unbundled|||Hardware, HP Ultrium-2 LTO Tape Drive, Firmware Download Program F
116326|01|Feb/03/04| | | |  |Unbundled|||Hardware, DLT8000 Tape Drive, Firmware Download Program, V87
116327|01|Feb/13/04| | | |  |Unbundled|||Hardware, Quantum DLT8000 Tape Drive, Firmware Download Program, V
116328|01|Mar/16/04| | | |  |Unbundled|||Hardware, Quantum DLT7000 Tape Drive, Firmware Download Program, V
116622|03|Nov/29/06| | | |  |Unbundled|||Hardware, HP Ultrium-2 LTO Tape Drive, Firmware Download Program F
116623|03|Jul/28/06| | | |  |Unbundled|||Hardware, Quantum SDLT320 Tape Drive, Firmware Download Program V9
116634|03|Sep/24/07| | | |  |Unbundled|||Hardware, HP LTO-2 Tape Drive, Firmware Download Program F63D
118170|06|Mar/25/09| | | |  |Unbundled|||Hardware, Quantum SDLT600 Tape Drive, Firmware Download Program V5
119391|01|Apr/06/05| | | |  |Unbundled|||L25/L100 Tape Library, FC420 Firmware, V1.47
120595|03|Oct/01/09| | | |  |Unbundled|||Hardware, HP LTO-3 Tape Drive, Firmware Download Program G67D
121738|01|Dec/19/05| | | |  |Unbundled|||Hardware, HP Ultrium-3 LTO Tape Drive, Firmware Download Program G
122133|03|Apr/11/07| | | |  |Unbundled|||Hardware, C2 Tape Autoloader, Firmware, V43
122134|05|Oct/17/08| | | |  |Unbundled|||Hardware, C4 Tape Library, Firmware, V51
123861|03|Apr/07/08| | | |  |Unbundled|||Hardware, LTO-3 Tape Drive, Firmware Download Program, G63Z
123862|02|Apr/07/08| | | |  |Unbundled|||Hardware, LTO-2V Tape Drive, Firmware Download Program, S63Z
124538|02|Apr/07/08| | | |  |Unbundled|||Hardware, LTO-3 Tape Drive, Firmware Download Program, L63Z
124728|02|Apr/07/08| | | |  |Unbundled|||Hardware, LTO-2 Tape Drive, Firmware Download Program, F6CZ
124773|01|Sep/24/07| | | |  |Unbundled|||Hardware, HP LTO-2V Tape Drive, Firmware Download Program S63D
126215|01|Apr/07/08| | | |  |Unbundled|||Hardware, LTO-3 Tape Drive, Firmware Download Program, M63Z
126216|01|Aug/30/07| | | |  |Unbundled|||Hardware, DAT72, SCSI, non-RoHS, Tape Drive, Firmware Download Pro
126805|02|Sep/29/09| | | |  |Unbundled|||Hardware, DAT72, SCSI, RoHS, Tape Drive, Firmware Download Program
126806|02|Sep/29/09| | | |  |Unbundled|||Hardware, DAT72, USB, RoHS, Tape Drive, Firmware Download Program,
128438|13|Feb/09/15| | | |  |Unbundled|||Sun StorageTek SL24 Tape Autoloader - F.20
128439|12|Feb/09/15| | | |  |Unbundled|||Sun StorageTek SL48 Tape Library - H.70
128549|12|Oct/01/13| | | |  |Unbundled|||Sun StorageTek LTO4 FC Tape Drive-C7QH
128629|11|Jan/30/13| | | |  |Unbundled|||Sun StorageTek LTO4 SCSI Tape Drive C7Q0
128630|09|Aug/06/14| | | |  |Unbundled|||Sun StorageTek LTO4 FC Tape Drive-H67S
128631|07|Jun/16/11| | | |  |Unbundled|||Sun StorageTek LTO4 SCSI Tape Drive-B63S
128634|03|Dec/08/09| | | |  |Unbundled|||Hardware, LTO-3 4Gb FC Tape Drive Firmware, M6BS
128635|03|Dec/08/09| | | |  |Unbundled|||Hardware, LTO-3 2Gb FC Tape Drive Firmware, L6HS
128636|03|Dec/08/09| | | |  |Unbundled|||Hardware, LTO-3 SCSI Tape Drive Firmware, G69S
136763|02|May/26/10| | | |  |Unbundled|||IBM LTO-2 FC Tape Drive Firmware, 66K8,  Library Family L180, L700
136764|02|May/26/10| | | |  |Unbundled|||IBM LTO-2 SCSI Tape Drive Firmware, 66K8,  Library Family L180, L7
137079|02|Apr/10/09| | | |  |Unbundled|||Hardware, Quantum DLTS4 Tape Drive, Firmware Download Program V42
138737|01|Apr/06/11| | | |  |Unbundled|||Hardware, LTO-3 4Gb FC Tape Drive Firmware for the SLXX Library Fa
138739|05|Jun/16/11| | | |  |Unbundled|||LTO-4 SCSI Tape Drive Firmware for the SLXX Library Family-B63W
138740|06|Jun/26/14| | | |  |Unbundled|||LTO-4 FC Tape Drive Firmware for the SLXX Library Family-H6EW
138741|07|Jun/26/14| | | |  |Unbundled|||Sun StorageTek LTO4HH SAS Tape Drive - U62W
139103|05|Feb/07/12| | | |  |Unbundled|||Sun StorageTek LTO4 HH SCSI Tape Drive - W61W
139125|02|Mar/25/09| | | |  |Unbundled|||Hardware, Quantum DLTS4 Tape Drive, Firmware Download Program V42
141880|03|Feb/07/12| | | |  |Unbundled|||LTO-4HH SCSI Tape Drive Firmware for the Desktop and 1U Rackmount
141881|04|Aug/03/14| | | |  |Unbundled|||LTO-4HH SAS Tape Drive Firmware for the Desktop and 1U Rackmount M
142181|01|Sep/11/09| | | |  |Unbundled|||Hardware, LTO-3HH SCSI Tape Drive Firmware for the SLXX Library Fa
142182|01|Sep/11/09| | | |  |Unbundled|||Hardware, LTO-3HH SAS Tape Drive Firmware for the SLXX Library Fam
142184|01|Oct/01/09| | | |  |Unbundled|||Hardware, HP LTO-3HH SCSI Tape Drive, Firmware Download Program D2
142185|01|Oct/01/09| | | |  |Unbundled|||Hardware, HP LTO-3HH SAS Tape Drive, Firmware Download Program C26
145421|07|Jun/23/14| | | |  |Unbundled|||Sun StorageTek LTO5 FC Tape Drive-I6BS
145422|05|Jun/26/14| | | |  |Unbundled|||Sun StorageTek LTO-5HH SAS Tape Drive-Z68W
145782|06|Jun/26/14| | | |  |Unbundled|||Sun StorageTek LTO5 FC Tape Drive-I6BW
145783|05|Jun/23/14| | | |  |Unbundled|||Sun StorageTek LTO5 SAS Tape Drive-X69S
145784|09|Aug/03/14| | | |  |Unbundled|||Sun StorageTek LTO5 FC Tape Drive-E4J0
146963|01|Apr/25/11| | | |  |Unbundled|||Hardware, LTO-3 4Gb FC Tape Drive Firmware for the SLXX Library Fa
148139|04|Aug/03/14| | | |  |Unbundled|||Sun StorageTek LTO5HH SAS Tape Drive-Z66D
148369|01|Dec/16/11| | | |  |Unbundled|||Sun StorageTek T10000A Tape Drive-1.48.105
148433|01|Dec/16/11| | | |  |Unbundled|||Sun StorageTek T10000B Tape Drive-1.48.205
150062|03|Jun/23/14| | | |  |Unbundled|||StorageTek LTO6 FC Tape Drive-J3ES
150063|03|Jun/24/14| | | |  |Unbundled|||StorageTek LTO6hh SAS Tape Drive-33ES
150683|04|Aug/03/14| | | |  |Unbundled|||Sun StorageTek LTO6 FH FC Tape Drive-E4J0
150685|02|Jun/24/14| | | |  |Unbundled|||StorageTek LTO6hh FC Tape Drive-23DS
150686|02|Jun/24/14| | | |  |Unbundled|||Sun StorageTek LTO5hh FC Tape Drive-Y68S
150687|02|Jun/24/14| | | |  |Unbundled|||Sun StorageTek LTO5hh SAS Tape Drive-Z68S
150874|03|Feb/09/15| | | |  |Unbundled|||Sun StorageTek LTO6HH SAS Tape Drive-353D

**Comment by richardatlateralblast** [comment]
Some basic support added:

./oort.rb -n SDLT320
SDLT320:
Hardware, SDLT320/SDLT220 Tape Drive, Firmware Download Program, V
https://support.oracle.com/epmos/faces/ui/patch/PatchDetail.jspx?patchId=116166-05
Hardware, SDLT320/SDLT220 Automation Tape Drive, Firmware Download
https://support.oracle.com/epmos/faces/ui/patch/PatchDetail.jspx?patchId=116167-02
Hardware, Quantum SDLT320 Tape Drive, Firmware Download Program V9
https://support.oracle.com/epmos/faces/ui/patch/PatchDetail.jspx?patchId=116623-03
