### ISSUE TITLE
Tape drive logic doesnt find some things and errors on others.

### ISSUE THREAD

**Issue by WildOne69** [lateralblast/oort#9]
newly added tape drive firmware logic code doesnt return matches and errors on others.
i didnt test every single one but heres a few:

examples:
./oort.rb -n DLT4000
cat ~/patchdiag.xref | grep "DLT4000"
107592|01|Apr/21/99| | | |  |Unbundled|||Hardware, Tape: DLT4000, 4700 Probe-scsi corrupt output

 ./oort.rb -n DDS-3
./oort.rb:281:in `search_prom_fw_page': empty range in char class: /[DDS-3|x00]/ (RegexpError)
	from ./oort.rb:2552:in `<main>'
cat ~/patchdiag.xref | grep "DDS-3"
108402|01|Nov/17/99| | | |  |Unbundled|||Hardware,DDS-3 4mm Tape Drive: Firmware Download Program L910 firm
112092|01|Oct/23/01| | | |  |Unbundled||108402-01;|Hardware/Tape: DDS-3 4mm Tape Drive Firmware Download Program L007
112093|01|Oct/23/01| | | |  |Unbundled|||Hardware DDS-3 4mm Tape Autoloader Firmware Version U007

./oort.rb -n L1800
cat ~/patchdiag.xref | grep "L1800"
108598|03|Apr/21/00| | | |  |Unbundled|108437-02;||Hardware, Tape: L1800,  Libraries

oort.rb -n L1000
cat ~/patchdiag.xref | grep "L1000"
109780|01|Jul/13/00| | | |  |Unbundled|||Hardware, Tape: L1000,  Libraries

./oort.rb -n L3500
cat ~/patchdiag.xref | grep "L3500"
112069|01|Feb/27/02| | | |  |Unbundled|108437-04;||Hardware, Tape: L3500, Libraries

./oort.rb -n DAT72
cat ~/patchdiag.xref | grep "DAT72"
126216|01|Aug/30/07| | | |  |Unbundled|||Hardware, DAT72, SCSI, non-RoHS, Tape Drive, Firmware Download Pro
126805|02|Sep/29/09| | | |  |Unbundled|||Hardware, DAT72, SCSI, RoHS, Tape Drive, Firmware Download Program
126806|02|Sep/29/09| | | |  |Unbundled|||Hardware, DAT72, USB, RoHS, Tape Drive, Firmware Download Program,

**Comment by richardatlateralblast** [comment]
Added handling for hyphens in some model numbers
